name: Pipeline-github

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:   # 🌍 Variables globales para todos los jobs
  Nexus_REPO_URL: ${{ vars.NEXUS_REPO_URL }}
  Nexus_REPO_USER: ${{ secrets.NEXUS_REPO_USER }}
  Nexus_REPO_PASS: ${{ secrets.NEXUS_REPO_PASS }}
  Nexus_IQ_USERNAME: ${{ secrets.IQ_USERNAME }}
  Nexus_IQ_PASSWORD: ${{ secrets.NEXUS_IQ_PASSWORD }}
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Maven
      run: mvn clean install --settings .m2/settings.xml
      #run: mvn -B package --file pom.xml
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: cobrojava-artifact
        path: target/

  sonatype-cli:
    runs-on: ubuntu-latest 
    needs: build
    steps:
      #Check out your code
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: cobrojava-artifact
          path: target
      # Perform an evaluation 
      - name: Run evaluate action 
        id: evaluate
        uses: sonatype/actions/evaluate@v1
        with:
          iq-server-url: http://52.234.210.127:8070/
          username: ${{ env.Nexus_IQ_USERNAME }}
          password: ${{ env.Nexus_IQ_PASSWORD }}
          application-id: CobroJava
          scan-targets: target/*.jar
          # upload-sarif-file: true
  
  DeployToNexusRepo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Deploy con Maven
        run: mvn $MAVEN_CLI_OPTS deploy -Dmaven.test.skip=true
   